# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 06:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20160329_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 29, 6, 51, 4, 659870, tzinfo=utc)),
        ),
    ]
